# Controlador Default
aac/hello:
    path:     /hello/{name}
    defaults: { _controller: AacBundle:Default:index }
aac/inicio:
    path:     /inicio
    defaults: { _controller: AacBundle:Default:inicio }
aac/servicios/profesionales:
    path:     /servicios/profesionales
    defaults: { _controller: AacBundle:Default:profesionales }
aac/servicios/voluntarios:
    path:     /servicios/voluntarios
    defaults: { _controller: AacBundle:Default:voluntarios }
aac/otros/servicios:
    path:     /servicios/otros
    defaults: { _controller: AacBundle:Default:otros }    
# Controlador Contacto
contacto:
    path:     /contacto
    defaults: { _controller: AacBundle:Contacto:contacto }
contacto_lista:
    path:     /contacto/lista
    defaults: { _controller: AacBundle:Contacto:lista }
contactos_ver:
    path:     /contacto/ver/{id}
    defaults: {_controller: AacBundle:Contacto:ver}
contactos_eliminar:
    path:     /contacto/eliminar/{id}
    defaults: {_controller: AacBundle:Contacto:eliminar}    
# Controlador Usuarios    
usuarios:
    path:     /usuarios
    defaults: { _controller: AacBundle:Usuarios:index }
usuarios_entrada:
    path:     /usuarios/inicio
    defaults: { _controller: AacBundle:Usuarios:inicio }    
usuarios_seleccion:
    path:     /usuarios/seleccionar
    defaults: { _controller: AacBundle:Usuarios:imprimir }    
usuarios_bloqueados:
    path:     /usuarios/bloqueados
    defaults: {_controller: AacBundle:Usuarios:bloqueados}    
usuarios_add:
    path:     /usuarios/add
    defaults: {_controller: AacBundle:Usuarios:add}
usuarios_modificar:
    path:     /usuarios/modificar/{id}
    defaults: {_controller: AacBundle:Usuarios:modificar}
usuarios_ver:
    path:     /usuarios/ver/{id}
    defaults: {_controller: AacBundle:Usuarios:ver}
usuarios_eliminar:
    path:     /usuarios/eliminar/{id}
    defaults: {_controller: AacBundle:Usuarios:eliminar}
# Controlador Archivos    
archivos:
    path:     /archivos
    defaults: { _controller: AacBundle:Archivo:index }    
archivos_subir:
    path:     /archivos/subir
    defaults: { _controller: AacBundle:Archivo:subir }
archivos_modificar:
    path:     /archivos/modificar/{id}
    defaults: {_controller: AacBundle:Archivo:modificar}
archivos_ver:
    path:     /archivos/ver/{id}
    defaults: {_controller: AacBundle:Archivo:ver}    
archivos_eliminar:
    path:     /archivos/eliminar/{id}
    defaults: {_controller: AacBundle:Archivo:eliminar}
# Controlador Email
enviar_email:
    path:     /email/enviar/{id}
    defaults: {_controller: AacBundle:Email:enviar}
enviar_email_todos:
    path:     /email/seleccion/{activo}
    defaults: {_controller: AacBundle:Email:seleccion}
email_texto:
    path:     /email/texto
    defaults: {_controller: AacBundle:Email:texto}
lista_email:
    path:     /email/listado/{id}
    defaults: {_controller: AacBundle:Email:lista}    
ver_email:
    path:     /email/ver/{id}
    defaults: {_controller: AacBundle:Email:ver}    