# Controlador Default
aac/hello:
    path:     /hello/{name}
    defaults: { _controller: AacBundle:Default:index }
aac/inicio:
    path:     /inicio
    defaults: { _controller: AacBundle:Default:inicio }
# Controlador Usuarios    
usuarios:
    path:     /usuarios
    defaults: { _controller: AacBundle:Usuarios:index }
usuarios_bloqueados:
    path:     /usuarios/bloqueados
    defaults: {_controller: AacBundle:Usuarios:bloqueados}    
usuarios_add:
    path:     /usuarios/add
    defaults: {_controller: AacBundle:Usuarios:add}
usuarios_modificar:
    path:     /usuarios/modificar/{id}
    defaults: {_controller: AacBundle:Usuarios:modificar}
usuarios_ver:
    path:     /usuarios/ver/{id}
    defaults: {_controller: AacBundle:Usuarios:ver}
usuarios_eliminar:
    path:     /usuarios/eliminar/{id}
    defaults: {_controller: AacBundle:Usuarios:eliminar}
# Controlador Archivos    
archivos:
    path:     /archivos
    defaults: { _controller: AacBundle:Archivo:index }    
archivos_subir:
    path:     /archivos/subir
    defaults: { _controller: AacBundle:Archivo:subir }
archivos_modificar:
    path:     /archivos/modificar/{id}
    defaults: {_controller: AacBundle:Archivo:modificar}
archivos_ver:
    path:     /archivos/ver/{id}
    defaults: {_controller: AacBundle:Archivo:ver}    
archivos_eliminar:
    path:     /archivos/eliminar/{id}
    defaults: {_controller: AacBundle:Archivo:eliminar}
# Controlador Email
enviar_email:
    path:     /email/enviar/{id}
    defaults: {_controller: AacBundle:Email:enviar}
enviar_email_todos:
    path:     /email/seleccion/{activo}
    defaults: {_controller: AacBundle:Email:seleccion}
email_texto:
    path:     /email/texto
    defaults: {_controller: AacBundle:Email:texto}
lista_email:
    path:     /email/listado/{id}
    defaults: {_controller: AacBundle:Email:lista}    
ver_email:
    path:     /email/{id}
    defaults: {_controller: AacBundle:Email:index}    