services:
#    aac.example:
#        class: Aac\AacBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
# Libreria My_hash
    Servicios:
        class:      Aac\AacBundle\Servicios\Servicios
        arguments:  [algoritmo, data, @service_container]
    EmailsServicio:
        class:      Aac\AacBundle\Servicios\EmailsServicio
        arguments:  [@service_container]

