<?php

namespace Aac\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
   
    public function buscarPorNivel($nivel)
    {
        return $this->_em->createQuery('SELECT u FROM AacUserBundle:User u '
                . 'WHERE u.nivel <= :nivel '
                . 'ORDER BY u.id ASC')
                ->setParameter('nivel', $nivel)
                ->getResult();        

    }
}
