<?php

namespace Aac\AacBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends EntityRepository
{
   
    public function findBuscarPorUsuario($idUser)
    {
        return $this->_em->createQuery('SELECT a FROM AacBundle:Archivo a '
                . 'WHERE a.de = :de '
                . 'OR a.para = :de '
                . 'OR a.para = :para9 '
                . 'ORDER BY a.id ASC')
                ->setParameter('de', $idUser)
                ->setParameter('para9', '99999')
                ->getResult();        

    }
}
