<?php

namespace Aac\AacBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRepository extends EntityRepository
{
    public function buscarTodos()
    {
        return $this->_em->createQuery('SELECT c FROM AacBundle:contacto c '
                . 'ORDER BY c.id ASC')
                ->getResult(); 
    }
    public function buscarId($id)
    {
        return $this->_em->createQuery('SELECT c FROM AacBundle:contacto c '
                . 'WHERE c.id = :id '
                . 'ORDER BY c.id ASC')
                ->setParameter('id', $id)
                ->getResult();
    }
}
