<?php

namespace Aac\AacBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function findBuscarPorUsuario($idUser)
    {
        return $this->_em->createQuery('SELECT e FROM AacBundle:email e '
                . 'WHERE e.para = :para '
                . 'ORDER BY e.id ASC')
                ->setParameter('para', $idUser)
                ->getResult();        

    }
}
