<?php

// autoload.php @generated by Composer

echo 'autoload raiz';exit;
require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInitd00e67f81cc5525fa7b03cb358a9dbee::getLoader();
